name: 'YAML Outputs'
description: 'Read a YAML file, flatten it recursively into a set of output parameters'

branding:
  icon: arrow-right
  color: green

inputs:
  file-path:
    required: true
    description: 'The path of the YAML file to read'

  separator:
    required: false
    description:
      'The separator used to concatenate child properties. For example,
      "root__parent__child: true"'
    default: '__'

  node:
    required: false
    description: 'The node to start flattening from. For example, "root.parent"'

  export-env-variables:
    required: false
    description: 'Export outputs as environment variables'
    default: true

  fail-on-file-not-found:
    required: false
    description:
      'Set to false if you do not want the action to fail if the file does not
      exist'
    default: true

runs:
  using: 'node20'
  main: 'dist/index.js'
